apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-advice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-advice
  template:
    metadata:
      labels:
        app: stock-advice
    spec:
      containers:
      - name: api
        image: stock-advice-app:latest
        imagePullPolicy: IfNotPresent  # Skip Docker Hub, use local
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: stock-advice-svc
spec:
  selector:
    app: stock-advice
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
